name: Update bump pr release comment

on:
  issue_comment:
    types:
      - created

jobs:
  update_release_comment:
    name: Update release comment
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/')
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------------
      # 1. Checkout to target branch
      # ----------------------------------------------
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      # ----------------------------------------------
      # 2. Setup Node environment
      # ----------------------------------------------
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # ----------------------------------------------
      # 3. Checkout to release branch
      # ----------------------------------------------
      - name: Checkout to release branch
        run: |
          CURRENT_VERSION=$(node -e "console.log(require('./package.json').version)")
          VERSION_MAJOR_MINOR=$(node -e "console.log(require('./package.json').version.split('.').slice(0, -1).join('.'))")
          git branch -r | grep origin/release/v$VERSION_MAJOR_MINOR$
          git checkout release/v$VERSION_MAJOR_MINOR
          git fetch --tag -f

      # ----------------------------------------------
      # 4. Cherry pick merge commit OR
      # ----------------------------------------------
      - name: Cherry pick merge commit
        if: startsWith(github.event.comment.body, '/cherry-pick')
        run: |
          message="${{ github.event.comment.body }}"
          message="${message:13}"

          git config user.name github-actions
          git config user.email github-actions@github.com
          git cherry-pick -m 1 $message

      # ----------------------------------------------
      # 4. Revert commit
      # ----------------------------------------------
      - name: Revert commit
        if: startsWith(github.event.comment.body, '/revert')
        run: |
          message="${{ github.event.comment.body }}"
          message="${message:8}"

          git config user.name github-actions
          git config user.email github-actions@github.com
          git revert -m 1 $message

      # ----------------------------------------------
      # 5. Push changes
      # ----------------------------------------------
      - name: Commit changes
        run: git push

      # ----------------------------------------------
      # 6. Generate changelog
      # ----------------------------------------------
      - name: Generate changelog
        id: changelog
        run: |
          changelog=$(gh api repos/$GITHUB_REPOSITORY/releases/generate-notes \
            -f tag_name="v$CURRENT_VERSION" \
            -f target_commitish=main)
          echo "::set-output name=body::${changelog.body}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ----------------------------------------------
      # 7. Get id of first comment
      # ----------------------------------------------
      - name: Find comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: Full Changelog

      # ----------------------------------------------
      # 8. Create release comment OR
      # ----------------------------------------------
      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.changelog.outputs.body }}

      # ----------------------------------------------
      # 8. Update release comment
      # ----------------------------------------------
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.changelog.outputs.body }}
